### ISSUE TITLE
Make name of nested function configurable

### ISSUE THREAD

**Issue by keddelzz** [keddelzz/hidden-args#24]
``` scala
@hiddenargs("loop")
def sum(xs: List[Int], @hidden acc: Int = 0): Int = 
  xs match {
    case Nil => acc
    case hd :: tl => sum(tl, acc + hd)
  }
```

The annotation `@hiddenargs` could get an optional parameter, which represents the name of the inner function, thus the code snipped above would expand to

``` scala
def sum(xs: List[Int], @hidden acc: Int = 0): Int = {
  def loop(xs: List[Int], acc: Int): Int = 
    xs match {
      case Nil => acc
      case hd :: tl => sum(tl, acc + hd)
    }

  loop(xs, 0)
}
```

.. instead of using the (synthetic) name `sum_impl`.

**Comment by rexim** [comment]
I suggest to generate a random name for the inner functions. Similar approach is used by lispers with function `gensym`, that generates a unique random symbol.

**Comment by keddelzz** [comment]
Instead of generating a random name for the inner function the name of the outer function + `_impl` is used currently. But the actual name of the inner function is not promised to the user in any way.

The remaining question is: Which name should be used?
- A name, that can be specified by the user.
- A random name.
- Some name, that is not specified (e.g. `<outer-function>` + `_impl`).

**Comment by keddelzz** [comment]
I won't make the name configurable, to achieve abstraction.
The user should neither depend on nor care about the name of the nested function (or method).
