### ISSUE TITLE
Publish stable version of hidden-args somewhere accessible via sbt

### ISSUE THREAD

**Issue by rexim** [keddelzz/hidden-args#25]
We came across the following problem during our release process: https://github.com/morganey-lang/Morganey/issues/271

We suspect that publishing a stable version of hidden-args somewhere could help us to resolve it easily. Is it possible to do that? Thanks!

**Comment by keddelzz** [comment]
Thanks for filing this issue!

## 

I'll have a look at releasing `hidden-args`! Unfortunately I can't promise that I'll be able to do that on the weekend.

**Comment by rexim** [comment]
@keddelzz cool, thanks! No worries, take your time! :)

**Comment by rexim** [comment]
@keddelzz thank you very much!

**Comment by keddelzz** [comment]
@rexim Sorry for taking so long.
